### ISSUE TITLE
XEP-0368: SRV records for XMPP over TLS

### ISSUE THREAD

**Issue by Neustradamus** [markdoliner/check_xmpp_dns#2]
It is possible to add xmpps SRV?
- https://xmpp.org/extensions/xep-0368.html

**Comment by markdoliner** [comment]
Ok, I made a bunch of changes and I believe this is working now. The new code is running on https://kingant.net/check_xmpp_dns/

If you happen to try it, please let me know if you see any flaws. Thanks, and sorry it took me three and a half years to respond to this!
